version: '3.8'
services:
  backend:
    build: ./backend
    container_name: dreamy-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - dreamy-net
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dreamy-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dreamy-net
networks:
  dreamy-net:
    driver: bridge 